# Generated by Django 5.1.7 on 2025-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.DeleteModel(
            name='BrokerProfile',
        ),
    ]
