# Generated by Django 5.1.7 on 2025-06-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='addetd_at',
            new_name='added_at',
        ),
    ]
