# Generated by Django 5.1.7 on 2025-05-12 23:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='is_fenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
