# Generated by Django 5.1.7 on 2025-05-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_properties_electricity_type_properties_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='broker',
        ),
    ]
