# Generated by Django 5.1.7 on 2025-06-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_properties_is_special_needs_properties_last_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
