# Generated by Django 5.1.7 on 2025-06-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertymedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(upload_to='properties/'),
        ),
    ]
