# Generated by Django 5.1.7 on 2025-06-27 12:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertymedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
