# Generated by Django 5.1.7 on 2025-05-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerReview',
        ),
    ]
