# Generated by Django 5.1.7 on 2025-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_delete_brokerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='rating',
            field=models.FloatField(),
        ),
    ]
